film_admin:
    resource: "@FilmAdminBundle/Controller/"
    type:     annotation
    prefix:   /

film_biblio:
    resource: "@FilmBiblioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
